use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let functions_dir = manifest_dir.join("src").join("functions");
    println!("cargo:rerun-if-changed={}", functions_dir.display());

    let mut files = Vec::new();
    collect_function_files(&functions_dir, &functions_dir, &mut files);
    files.sort();

    let mut generated = String::from("// @generated by build.rs\n");
    for path in files {
        println!("cargo:rerun-if-changed={}", path.display());
        let rel = path
            .strip_prefix(&functions_dir)
            .expect("function file under functions dir");
        let module_name = generated_module_name(rel);
        generated.push_str(&format!(
            "#[path = {:?}]\nmod {};\n",
            path.to_string_lossy(),
            module_name
        ));
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    fs::write(out_dir.join("function_modules.rs"), generated).expect("write generated modules");
}

fn collect_function_files(root: &Path, current: &Path, files: &mut Vec<PathBuf>) {
    let entries = fs::read_dir(current).expect("read functions dir");
    for entry in entries {
        let entry = entry.expect("read functions entry");
        let path = entry.path();
        if path.is_dir() {
            collect_function_files(root, &path, files);
            continue;
        }

        if path.extension().and_then(|ext| ext.to_str()) != Some("rs") {
            continue;
        }

        let rel = path.strip_prefix(root).expect("relative path");
        if rel.components().count() < 2 {
            continue;
        }

        let stem = path.file_stem().and_then(|s| s.to_str()).unwrap_or("");
        if matches!(stem, "mod" | "prelude" | "registry") {
            continue;
        }

        files.push(path);
    }
}

fn generated_module_name(path: &Path) -> String {
    let mut name = String::from("__xlite_function");
    for component in path.components() {
        name.push('_');
        let part = component.as_os_str().to_string_lossy();
        for ch in part.chars() {
            if ch.is_ascii_alphanumeric() {
                name.push(ch.to_ascii_lowercase());
            } else {
                name.push('_');
            }
        }
    }
    name
}
