#!/usr/bin/env python3
"""Deterministically generate M0 API consumers and canonical prose views."""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import tempfile
from pathlib import Path
from typing import Any

import yaml


ROOT = Path(__file__).resolve().parents[1]


def load_yaml(relative: str) -> dict[str, Any]:
    with (ROOT / relative).open(encoding="utf-8") as handle:
        return yaml.safe_load(handle)


def digest(relative: str) -> str:
    return hashlib.sha256((ROOT / relative).read_bytes()).hexdigest()


def operations(openapi: dict[str, Any]) -> list[dict[str, Any]]:
    result: list[dict[str, Any]] = []
    for path, path_item in openapi["paths"].items():
        for method in ("get", "post", "put", "patch", "delete"):
            if method not in path_item:
                continue
            operation = path_item[method]
            result.append({"id": operation["operationId"], "method": method.upper(), "path": path})
    return sorted(result, key=lambda item: item["id"])


def go_name(operation_id: str) -> str:
    return operation_id[:1].upper() + operation_id[1:]


def generate_go(openapi: dict[str, Any]) -> str:
    ops = operations(openapi)
    constants = "\n".join(f'\tOperation{go_name(op["id"])} OperationID = "{op["id"]}"' for op in ops)
    interface = "\n".join(
        f"\t{go_name(op['id'])}(context.Context, Request) (Response, error)" for op in ops
    )
    routes = "\n".join(
        f'\tmux.HandleFunc("{op["method"]} {op["path"]}", adapt(handler.{go_name(op["id"])}))'
        for op in ops
    )
    source = f'''// Code generated by scripts/generate.py from contracts/openapi.yaml; DO NOT EDIT.
// Contract SHA-256: {digest("contracts/openapi.yaml")}
package generated

import (
    "context"
    "encoding/json"
    "net/http"
)

type OperationID string

const (
{constants}
)

type Request struct {{
    HTTPRequest *http.Request
    Body json.RawMessage
}}

type Response struct {{
    Status int
    Body any
}}

type Handler interface {{
{interface}
}}

func RegisterHandlers(mux *http.ServeMux, handler Handler) {{
{routes}
}}

type operationHandler func(context.Context, Request) (Response, error)

func adapt(handler operationHandler) http.HandlerFunc {{
    return func(writer http.ResponseWriter, request *http.Request) {{
        var body json.RawMessage
        if request.Body != nil {{
            defer request.Body.Close()
            decoder := json.NewDecoder(request.Body)
            if err := decoder.Decode(&body); err != nil && err.Error() != "EOF" {{
                http.Error(writer, "invalid JSON", http.StatusBadRequest)
                return
            }}
        }}
        response, err := handler(request.Context(), Request{{HTTPRequest: request, Body: body}})
        if err != nil {{
            http.Error(writer, "unimplemented", http.StatusNotImplemented)
            return
        }}
        writer.Header().Set("Content-Type", "application/json")
        writer.WriteHeader(response.Status)
        _ = json.NewEncoder(writer).Encode(response.Body)
    }}
}}
'''
    return subprocess.run(
        ["gofmt"], input=source, check=True, text=True, capture_output=True
    ).stdout


def ts_path_expression(path: str) -> str:
    expression = path
    for parameter in ("org_id", "project_id"):
        expression = expression.replace("{" + parameter + "}", "${encodeURIComponent(params." + parameter + ")}")
    return "`" + expression + "`"


def generate_typescript(openapi: dict[str, Any]) -> str:
    ops = operations(openapi)
    methods: list[str] = []
    for op in ops:
        path_parameters = re_path_parameters(op["path"])
        parameter_type = "{ " + "; ".join(f"{name}: string" for name in path_parameters) + " }" if path_parameters else "Record<string, never>"
        has_body = op["method"] != "GET"
        body_argument = ", body: unknown" if has_body else ""
        idempotency = "\n      ...(options.idempotencyKey ? { 'Idempotency-Key': options.idempotencyKey } : {})," if has_body and op["id"] != "login" else ""
        body_line = "\n    body: JSON.stringify(body)," if has_body else ""
        methods.append(f'''  async {op["id"]}(params: {parameter_type}{body_argument}, options: RequestOptions = {{}}): Promise<unknown> {{
    return this.request({ts_path_expression(op["path"])}, {{
      method: "{op["method"]}",
      headers: {{{idempotency}
        ...options.headers,
      }},{body_line}
    }});
  }}''')
    return f'''// Code generated by scripts/generate.py from contracts/openapi.yaml; DO NOT EDIT.
// Contract SHA-256: {digest("contracts/openapi.yaml")}

export type RequestOptions = {{
  headers?: Record<string, string>;
  idempotencyKey?: string;
}};

export const operationIds = {json.dumps([op["id"] for op in ops], indent=2)} as const;
export type OperationId = (typeof operationIds)[number];

export class WorkplaneClient {{
  constructor(
    private readonly baseUrl: string,
    private readonly fetcher: typeof fetch = fetch,
  ) {{}}

{chr(10).join(methods)}

  private async request(path: string, init: RequestInit): Promise<unknown> {{
    const response = await this.fetcher(`${{this.baseUrl}}${{path}}`, {{
      ...init,
      headers: {{ "Content-Type": "application/json", ...init.headers }},
    }});
    const payload: unknown = await response.json();
    if (!response.ok) throw new WorkplaneProblem(response.status, payload);
    return payload;
  }}
}}

export class WorkplaneProblem extends Error {{
  constructor(public readonly status: number, public readonly payload: unknown) {{
    super(`Workplane request failed (${{status}})`);
  }}
}}
'''


def re_path_parameters(path: str) -> list[str]:
    return [segment[1:-1] for segment in path.split("/") if segment.startswith("{")]


def markdown_table(headers: list[str], rows: list[list[str]]) -> str:
    output = ["| " + " | ".join(headers) + " |", "| " + " | ".join("---" for _ in headers) + " |"]
    output.extend("| " + " | ".join(cell.replace("|", "\\|") for cell in row) + " |" for row in rows)
    return "\n".join(output)


def generate_lifecycles(contract: dict[str, Any]) -> str:
    sections = [
        "# Generated lifecycle contract",
        "",
        "<!-- Generated by scripts/generate.py. Do not edit. -->",
        f"<!-- Source SHA-256: {digest('contracts/lifecycles.yaml')} -->",
        "",
        "Default policy: **deny**.",
    ]
    for name in ("project", "deliverable", "gate", "work_item"):
        machine = contract[name]
        rows = []
        for transition in machine.get("transitions", []):
            rows.append([
                str(transition["from"]),
                str(transition["command"]),
                str(transition["to"]),
                str(transition.get("mode", "all")),
                str(transition.get("requires", "")),
            ])
        sections.extend(["", f"## {name.replace('_', ' ').title()}", "", f"States: `{', '.join(machine['states'])}`.", "", markdown_table(["From", "Command", "To", "Mode/kind", "Requires"], rows)])
    dates = contract["rules"][0]
    sections.extend(["", "## Date rule", "", f"`{dates['id']}` applies to `{', '.join(dates['applies_to'])}` and permits attention only; forbidden effects are `{', '.join(dates['forbidden_effects'])}`.", ""])
    return "\n".join(sections)


def generate_permissions(contract: dict[str, Any]) -> str:
    action_rows = [[family, action, "yes" if action in contract["human_required"] else "no"] for family, actions in contract["actions"].items() for action in actions]
    role_rows = [[scope, role] for scope, roles in contract["roles"].items() for role in roles]
    return "\n".join([
        "# Generated permission vocabulary",
        "",
        "<!-- Generated by scripts/generate.py. Do not edit. -->",
        f"<!-- Source SHA-256: {digest('contracts/permissions.yaml')} -->",
        "",
        "Default policy: **deny**. Action qualifiers are forbidden.",
        "",
        "## Roles", "", markdown_table(["Scope", "Role"], role_rows),
        "", "## Actions", "", markdown_table(["Family", "Action", "Human required"], action_rows), "",
    ])


def generate_expected_denies() -> str:
    permissions = load_yaml("contracts/permissions.yaml")
    operations_contract = load_yaml("contracts/operation-permissions.yaml")
    expected = load_yaml("contracts/expected-denies.yaml")
    actions = sorted(action for family in permissions["actions"].values() for action in family)
    universal = [template["id"] for template in expected["templates"] if template["applies_to"] == "all_actions"]
    human = [template["id"] for template in expected["templates"] if template["applies_to"] == "human_required_actions"]
    payload = {
        "schema_version": 1,
        "sources": {
            "permissions": digest("contracts/permissions.yaml"),
            "operation_permissions": digest("contracts/operation-permissions.yaml"),
            "expected_denies": digest("contracts/expected-denies.yaml"),
        },
        "actions": [
            {
                "action": action,
                "deny_templates": universal + (human if action in permissions["human_required"] else []),
            }
            for action in actions
        ],
        "operations": [
            {
                "operation": operation,
                "actions": operation_actions,
                "deny_templates": sorted({template for action in operation_actions for template in universal + (human if action in permissions["human_required"] else [])}),
            }
            for operation, operation_actions in sorted(operations_contract["operations"].items())
        ],
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def render() -> dict[str, str]:
    openapi = load_yaml("contracts/openapi.yaml")
    return {
        "internal/api/generated/server.gen.go": generate_go(openapi),
        "web/src/api/client.gen.ts": generate_typescript(openapi),
        "docs/generated/lifecycles.md": generate_lifecycles(load_yaml("contracts/lifecycles.yaml")),
        "docs/generated/permissions.md": generate_permissions(load_yaml("contracts/permissions.yaml")),
        "tests/registries/expected-denies.generated.json": generate_expected_denies(),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()
    generated = render()
    drift: list[str] = []
    for relative, content in generated.items():
        path = ROOT / relative
        normalized = content.rstrip() + "\n"
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != normalized:
                drift.append(relative)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(normalized, encoding="utf-8")
    if args.self_test:
        with tempfile.TemporaryDirectory() as directory:
            mutated = Path(directory) / "permissions.md"
            mutated.write_text(generated["docs/generated/permissions.md"] + "twin author drift\n", encoding="utf-8")
            if mutated.read_text(encoding="utf-8") == generated["docs/generated/permissions.md"]:
                raise SystemExit("generation self-test failed to detect mutation")
        print("generation self-test passed: generated artifact drift detected")
        return 0
    if drift:
        print("generated artifact drift: " + ", ".join(drift))
        return 1
    print("generated artifacts are deterministic and current" if args.check else "generated artifacts updated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
