// Code generated by scripts/generate.py from contracts/openapi.yaml; DO NOT EDIT.
// Contract SHA-256: dbd041f81e9adb3f53ecc75ac9989f475a36e72727f219e7e66955c86cc92f73

export type LoginRequest = {
  email: string;
  password: string;
};

export type Session = {
  actor_id: string;
  actor_kind: "human";
  expires_at: string;
  csrf_token: string;
};

export type CreateExplorationProject = {
  title: string;
  outcome: string;
  hypothesis: string;
  falsifier: string;
  decision_criteria: Array<string>;
  experiment_bound: string;
};

export type Project = {
  id: string;
  organization_id: string;
  title: string;
  outcome: string;
  mode: "exploration" | "exploitation";
  state: "proposed" | "active" | "held" | "completed" | "stopped" | "cancelled";
  version: number;
  hypothesis: string;
  falsifier: string;
  decision_criteria: Array<string>;
  experiment_bound: string;
};

export type RecordDecision = {
  kind: "continue";
  question: string;
  choice: string;
  alternatives: Array<string>;
  rationale: string;
  evidence: Array<string>;
  consequences: Array<string>;
};

export type Decision = {
  id: string;
  project_id: string;
  actor_id: string;
  actor_kind: "human" | "agent";
  principal_id: string | null;
  recorded_at: string;
  kind: "continue";
  question: string;
  choice: string;
  alternatives: Array<string>;
  rationale: string;
  evidence: Array<string>;
  consequences: Array<string>;
};

export type Activity = {
  event_id: string;
  event_type: string;
  actor_id: string;
  actor_kind: "human" | "agent";
  principal_id: string | null;
  aggregate_version: number;
  command_id: string;
  request_id: string;
  occurred_at: string;
};

export type Problem = {
  type: string;
  title: string;
  status: number;
  code: string;
  request_id: string;
  detail?: string;
};

export type HumanSessionSecurity = {
  kind: "human-session";
  csrfToken?: string;
};

export type HumanMutationSecurity = {
  kind: "human-session";
  csrfToken: string;
};

export type AgentBearerSecurity = {
  kind: "agent-bearer";
  bearerToken: string;
};

export type RequestSecurity = HumanSessionSecurity | AgentBearerSecurity;

export type RequestOptions = {
  headers?: Record<string, string>;
  security?: RequestSecurity;
};

export type AuthenticatedOptions = RequestOptions;
export type VersionETag = `"${number}"`;
export type MutationOptions = Omit<RequestOptions, "security"> & {
  idempotencyKey: string;
  security: HumanMutationSecurity | AgentBearerSecurity;
};
export type VersionedMutationOptions = MutationOptions & {
  expectedVersion: VersionETag;
};
export type VersionedResponse<T> = {
  body: T;
  version: VersionETag;
};

type TransportResponse = {
  body: unknown;
  headers: Headers;
};

type RuntimeSchema = {
  type?: string | ReadonlyArray<string>;
  required?: ReadonlyArray<string>;
  additionalProperties?: boolean;
  properties?: Readonly<Record<string, RuntimeSchema>>;
  items?: RuntimeSchema;
  enum?: ReadonlyArray<unknown>;
  pattern?: string;
  minLength?: number;
  maxLength?: number;
  minItems?: number;
  maxItems?: number;
};

const versionETagPattern = /^"[1-9][0-9]*"$/;
const contractOwnedRequestHeaders = new Set([
  "authorization",
  "idempotency-key",
  "if-match",
  "x-csrf-token"
]);
export const requestBodyMaxBytes = 65536;
export const requestContractSchemas = {
  "LoginRequest": {
    "type": "object",
    "additionalProperties": false,
    "required": [
      "email",
      "password"
    ],
    "properties": {
      "email": {
        "type": "string",
        "format": "email",
        "minLength": 1,
        "maxLength": 320
      },
      "password": {
        "type": "string",
        "minLength": 1,
        "maxLength": 1024
      }
    }
  },
  "CreateExplorationProject": {
    "type": "object",
    "additionalProperties": false,
    "required": [
      "title",
      "outcome",
      "hypothesis",
      "falsifier",
      "decision_criteria",
      "experiment_bound"
    ],
    "properties": {
      "title": {
        "type": "string",
        "minLength": 1,
        "maxLength": 200,
        "pattern": "\\S"
      },
      "outcome": {
        "type": "string",
        "minLength": 1,
        "maxLength": 2000,
        "pattern": "\\S"
      },
      "hypothesis": {
        "type": "string",
        "minLength": 1,
        "maxLength": 2000,
        "pattern": "\\S"
      },
      "falsifier": {
        "type": "string",
        "minLength": 1,
        "maxLength": 2000,
        "pattern": "\\S"
      },
      "decision_criteria": {
        "type": "array",
        "minItems": 1,
        "maxItems": 32,
        "items": {
          "type": "string",
          "minLength": 1,
          "maxLength": 500,
          "pattern": "\\S"
        }
      },
      "experiment_bound": {
        "type": "string",
        "minLength": 1,
        "maxLength": 1000,
        "pattern": "\\S"
      }
    }
  },
  "RecordDecision": {
    "type": "object",
    "additionalProperties": false,
    "required": [
      "kind",
      "question",
      "choice",
      "alternatives",
      "rationale",
      "evidence",
      "consequences"
    ],
    "properties": {
      "kind": {
        "type": "string",
        "enum": [
          "continue"
        ]
      },
      "question": {
        "type": "string",
        "minLength": 1,
        "maxLength": 2000,
        "pattern": "\\S"
      },
      "choice": {
        "type": "string",
        "minLength": 1,
        "maxLength": 2000,
        "pattern": "\\S"
      },
      "alternatives": {
        "type": "array",
        "maxItems": 32,
        "items": {
          "type": "string",
          "maxLength": 1000
        }
      },
      "rationale": {
        "type": "string",
        "minLength": 1,
        "maxLength": 4000,
        "pattern": "\\S"
      },
      "evidence": {
        "type": "array",
        "maxItems": 64,
        "items": {
          "type": "string",
          "maxLength": 2000
        }
      },
      "consequences": {
        "type": "array",
        "maxItems": 32,
        "items": {
          "type": "string",
          "maxLength": 2000
        }
      }
    }
  }
} as const;
const requestContractParameters = {
  "IdempotencyKey": {
    "type": "string",
    "minLength": 16,
    "maxLength": 128
  },
  "ExpectedVersion": {
    "type": "string",
    "pattern": "^\"[1-9][0-9]*\"$",
    "examples": [
      "\"7\""
    ]
  }
} as const;
type RequestContractSchemaName = keyof typeof requestContractSchemas;
type RequestContractParameterName = keyof typeof requestContractParameters;

export const operationIds = [
  "createProject",
  "getProject",
  "listProjectActivity",
  "login",
  "recordDecision"
] as const;
export type OperationId = (typeof operationIds)[number];

export class WorkplaneClient {
  constructor(
    private readonly baseUrl: string,
    private readonly fetcher: typeof fetch = globalThis.fetch.bind(globalThis),
  ) {}

  async createProject(params: { org_id: string }, body: CreateExplorationProject, options: MutationOptions): Promise<Project> {
    this.validateParameter("IdempotencyKey", options.idempotencyKey);
    return (await this.request(`/api/v1/orgs/${encodeURIComponent(params.org_id)}/projects`, {
      method: "POST",
      headers: {
        ...this.extensionHeaders(options.headers),
      'Idempotency-Key': options.idempotencyKey,
        ...this.securityHeaders(options.security),
      },
    body: this.validateRequestBody("CreateExplorationProject", body),
    })).body as Project;
  }
  async getProject(params: { project_id: string }, options: AuthenticatedOptions = {}): Promise<Project> {
    return (await this.request(`/api/v1/projects/${encodeURIComponent(params.project_id)}`, {
      method: "GET",
      headers: {
        ...this.extensionHeaders(options.headers),
        ...this.securityHeaders(options.security),
      },
    })).body as Project;
  }
  async listProjectActivity(params: { project_id: string }, options: AuthenticatedOptions = {}): Promise<Array<Activity>> {
    return (await this.request(`/api/v1/projects/${encodeURIComponent(params.project_id)}/activity`, {
      method: "GET",
      headers: {
        ...this.extensionHeaders(options.headers),
        ...this.securityHeaders(options.security),
      },
    })).body as Array<Activity>;
  }
  async login(params: Record<string, never>, body: LoginRequest, options: RequestOptions = {}): Promise<Session> {
    return (await this.request(`/api/v1/session/login`, {
      method: "POST",
      headers: {
        ...this.extensionHeaders(options.headers),
        ...this.securityHeaders(options.security),
      },
    body: this.validateRequestBody("LoginRequest", body),
    })).body as Session;
  }
  async recordDecision(params: { project_id: string }, body: RecordDecision, options: VersionedMutationOptions): Promise<VersionedResponse<Decision>> {
    this.validateParameter("IdempotencyKey", options.idempotencyKey);
    this.validateParameter("ExpectedVersion", options.expectedVersion);
    const response = await this.request(`/api/v1/projects/${encodeURIComponent(params.project_id)}/decisions`, {
      method: "POST",
      headers: {
        ...this.extensionHeaders(options.headers),
      'Idempotency-Key': options.idempotencyKey,
      'If-Match': options.expectedVersion,
        ...this.securityHeaders(options.security),
      },
    body: this.validateRequestBody("RecordDecision", body),
    });
    const version = response.headers.get("ETag");
    if (version === null || !versionETagPattern.test(version)) {
      throw new WorkplaneContractError("recordDecision response omitted a valid ETag");
    }
    return { body: response.body as Decision, version: version as VersionETag };
  }

  private async request(path: string, init: RequestInit): Promise<TransportResponse> {
    const response = await this.fetcher(`${this.baseUrl}${path}`, {
      ...init,
      credentials: "same-origin",
      headers: { "Content-Type": "application/json", ...init.headers },
    });
    const payload: unknown = await response.json();
    if (!response.ok) throw new WorkplaneProblem(response.status, payload);
    return { body: payload, headers: response.headers };
  }

  private validateRequestBody(schemaName: RequestContractSchemaName, body: unknown): string {
    this.validateSchema(requestContractSchemas[schemaName], body, schemaName);
    const encoded = JSON.stringify(body);
    if (encoded === undefined) {
      throw new WorkplaneContractError(`${schemaName} cannot be serialized as JSON`);
    }
    if (new TextEncoder().encode(encoded).byteLength > requestBodyMaxBytes) {
      throw new WorkplaneContractError(`${schemaName} exceeds the ${requestBodyMaxBytes} byte request limit`);
    }
    return encoded;
  }

  private validateParameter(name: RequestContractParameterName, value: unknown): void {
    this.validateSchema(requestContractParameters[name], value, name);
  }

  private validateSchema(schema: RuntimeSchema, value: unknown, path: string): void {
    if (schema.type === "object") {
      if (value === null || typeof value !== "object" || Array.isArray(value)) {
        throw new WorkplaneContractError(`${path} must be an object`);
      }
      const record = value as Record<string, unknown>;
      for (const required of schema.required ?? []) {
        if (!Object.hasOwn(record, required)) {
          throw new WorkplaneContractError(`${path}.${required} is required`);
        }
      }
      if (schema.additionalProperties === false) {
        const allowed = new Set(Object.keys(schema.properties ?? {}));
        const unknown = Object.keys(record).find((key) => !allowed.has(key));
        if (unknown !== undefined) {
          throw new WorkplaneContractError(`${path}.${unknown} is not declared by OpenAPI`);
        }
      }
      for (const [name, propertySchema] of Object.entries(schema.properties ?? {})) {
        if (Object.hasOwn(record, name)) this.validateSchema(propertySchema, record[name], `${path}.${name}`);
      }
      return;
    }
    if (schema.type === "array") {
      if (!Array.isArray(value)) throw new WorkplaneContractError(`${path} must be an array`);
      if (schema.minItems !== undefined && value.length < schema.minItems) {
        throw new WorkplaneContractError(`${path} must contain at least ${schema.minItems} items`);
      }
      if (schema.maxItems !== undefined && value.length > schema.maxItems) {
        throw new WorkplaneContractError(`${path} must contain at most ${schema.maxItems} items`);
      }
      if (schema.items !== undefined) {
        value.forEach((item, index) => this.validateSchema(schema.items!, item, `${path}[${index}]`));
      }
      return;
    }
    if (schema.type === "string") {
      if (typeof value !== "string") throw new WorkplaneContractError(`${path} must be a string`);
      const length = Array.from(value).length;
      if (schema.minLength !== undefined && length < schema.minLength) {
        throw new WorkplaneContractError(`${path} must contain at least ${schema.minLength} characters`);
      }
      if (schema.maxLength !== undefined && length > schema.maxLength) {
        throw new WorkplaneContractError(`${path} must contain at most ${schema.maxLength} characters`);
      }
      if (schema.enum !== undefined && !schema.enum.includes(value)) {
        throw new WorkplaneContractError(`${path} is not an allowed value`);
      }
      if (schema.pattern !== undefined && !new RegExp(schema.pattern, "u").test(value)) {
        throw new WorkplaneContractError(`${path} does not match the public contract`);
      }
    }
  }

  private securityHeaders(security?: RequestSecurity): Record<string, string> {
    if (security?.kind === "agent-bearer") {
      return { Authorization: `Bearer ${security.bearerToken}` };
    }
    if (security?.kind === "human-session" && security.csrfToken !== undefined) {
      return { "X-CSRF-Token": security.csrfToken };
    }
    return {};
  }

  private extensionHeaders(headers?: Record<string, string>): Record<string, string> {
    return Object.fromEntries(
      Object.entries(headers ?? {}).filter(
        ([name]) => !contractOwnedRequestHeaders.has(name.toLowerCase()),
      ),
    );
  }
}

export class WorkplaneProblem extends Error {
  constructor(public readonly status: number, public readonly payload: unknown) {
    super(`Workplane request failed (${status})`);
  }
}

export class WorkplaneContractError extends Error {}
