// Code generated by scripts/generate.py from contracts/openapi.yaml; DO NOT EDIT.
// Contract SHA-256: d7f5589661ccff6fdcf9635d241483bdfec5429ce593377558a1188e509b17f6

export type Session = {
  actor_id: string;
  actor_kind: "human";
  expires_at: string;
  csrf_token: string;
};

export type HumanSessionSecurity = {
  kind: "human-session";
  csrfToken?: string;
};

export type HumanMutationSecurity = {
  kind: "human-session";
  csrfToken: string;
};

export type AgentBearerSecurity = {
  kind: "agent-bearer";
  bearerToken: string;
};

export type RequestSecurity = HumanSessionSecurity | AgentBearerSecurity;

export type RequestOptions = {
  headers?: Record<string, string>;
  security?: RequestSecurity;
};

export type AuthenticatedOptions = RequestOptions;
export type VersionETag = `"${number}"`;
export type MutationOptions = Omit<RequestOptions, "security"> & {
  idempotencyKey: string;
  security: HumanMutationSecurity | AgentBearerSecurity;
};
export type VersionedMutationOptions = MutationOptions & {
  expectedVersion: VersionETag;
};
export type VersionedResponse<T> = {
  body: T;
  version: VersionETag;
};

type TransportResponse = {
  body: unknown;
  headers: Headers;
};

const versionETagPattern = /^"[1-9][0-9]*"$/;
const contractOwnedRequestHeaders = new Set([
  "authorization",
  "idempotency-key",
  "if-match",
  "x-csrf-token"
]);

export const operationIds = [
  "createProject",
  "getProject",
  "listProjectActivity",
  "login",
  "recordDecision"
] as const;
export type OperationId = (typeof operationIds)[number];

export class WorkplaneClient {
  constructor(
    private readonly baseUrl: string,
    private readonly fetcher: typeof fetch = fetch,
  ) {}

  async createProject(params: { org_id: string }, body: unknown, options: MutationOptions): Promise<unknown> {
    return (await this.request(`/api/v1/orgs/${encodeURIComponent(params.org_id)}/projects`, {
      method: "POST",
      headers: {
        ...this.extensionHeaders(options.headers),
      'Idempotency-Key': options.idempotencyKey,
        ...this.securityHeaders(options.security),
      },
    body: JSON.stringify(body),
    })).body;
  }
  async getProject(params: { project_id: string }, options: AuthenticatedOptions = {}): Promise<unknown> {
    return (await this.request(`/api/v1/projects/${encodeURIComponent(params.project_id)}`, {
      method: "GET",
      headers: {
        ...this.extensionHeaders(options.headers),
        ...this.securityHeaders(options.security),
      },
    })).body;
  }
  async listProjectActivity(params: { project_id: string }, options: AuthenticatedOptions = {}): Promise<unknown> {
    return (await this.request(`/api/v1/projects/${encodeURIComponent(params.project_id)}/activity`, {
      method: "GET",
      headers: {
        ...this.extensionHeaders(options.headers),
        ...this.securityHeaders(options.security),
      },
    })).body;
  }
  async login(params: Record<string, never>, body: unknown, options: RequestOptions = {}): Promise<Session> {
    return (await this.request(`/api/v1/session/login`, {
      method: "POST",
      headers: {
        ...this.extensionHeaders(options.headers),
        ...this.securityHeaders(options.security),
      },
    body: JSON.stringify(body),
    })).body as Session;
  }
  async recordDecision(params: { project_id: string }, body: unknown, options: VersionedMutationOptions): Promise<VersionedResponse<unknown>> {
    const response = await this.request(`/api/v1/projects/${encodeURIComponent(params.project_id)}/decisions`, {
      method: "POST",
      headers: {
        ...this.extensionHeaders(options.headers),
      'Idempotency-Key': options.idempotencyKey,
      'If-Match': options.expectedVersion,
        ...this.securityHeaders(options.security),
      },
    body: JSON.stringify(body),
    });
    const version = response.headers.get("ETag");
    if (version === null || !versionETagPattern.test(version)) {
      throw new WorkplaneContractError("recordDecision response omitted a valid ETag");
    }
    return { body: response.body, version: version as VersionETag };
  }

  private async request(path: string, init: RequestInit): Promise<TransportResponse> {
    const response = await this.fetcher(`${this.baseUrl}${path}`, {
      ...init,
      credentials: "same-origin",
      headers: { "Content-Type": "application/json", ...init.headers },
    });
    const payload: unknown = await response.json();
    if (!response.ok) throw new WorkplaneProblem(response.status, payload);
    return { body: payload, headers: response.headers };
  }

  private securityHeaders(security?: RequestSecurity): Record<string, string> {
    if (security?.kind === "agent-bearer") {
      return { Authorization: `Bearer ${security.bearerToken}` };
    }
    if (security?.kind === "human-session" && security.csrfToken !== undefined) {
      return { "X-CSRF-Token": security.csrfToken };
    }
    return {};
  }

  private extensionHeaders(headers?: Record<string, string>): Record<string, string> {
    return Object.fromEntries(
      Object.entries(headers ?? {}).filter(
        ([name]) => !contractOwnedRequestHeaders.has(name.toLowerCase()),
      ),
    );
  }
}

export class WorkplaneProblem extends Error {
  constructor(public readonly status: number, public readonly payload: unknown) {
    super(`Workplane request failed (${status})`);
  }
}

export class WorkplaneContractError extends Error {}
