// Code generated by scripts/generate.py from contracts/openapi.yaml; DO NOT EDIT.
// Contract SHA-256: 9079c4e7a0d3170069ef6d81545984fe03855f2566412b5472c0a38e424aab96

export type HumanSessionSecurity = {
  kind: "human-session";
  csrfToken?: string;
};

export type HumanMutationSecurity = {
  kind: "human-session";
  csrfToken: string;
};

export type AgentBearerSecurity = {
  kind: "agent-bearer";
  bearerToken: string;
};

export type RequestSecurity = HumanSessionSecurity | AgentBearerSecurity;

export type RequestOptions = {
  headers?: Record<string, string>;
  security?: RequestSecurity;
};

export type AuthenticatedOptions = RequestOptions;
export type VersionETag = `"${number}"`;
export type MutationOptions = Omit<RequestOptions, "security"> & {
  idempotencyKey: string;
  security: HumanMutationSecurity | AgentBearerSecurity;
};
export type VersionedMutationOptions = MutationOptions & {
  expectedVersion: VersionETag;
};

export const operationIds = [
  "createProject",
  "getProject",
  "listProjectActivity",
  "login",
  "recordDecision"
] as const;
export type OperationId = (typeof operationIds)[number];

export class WorkplaneClient {
  constructor(
    private readonly baseUrl: string,
    private readonly fetcher: typeof fetch = fetch,
  ) {}

  async createProject(params: { org_id: string }, body: unknown, options: MutationOptions): Promise<unknown> {
    return this.request(`/api/v1/orgs/${encodeURIComponent(params.org_id)}/projects`, {
      method: "POST",
      headers: {
      'Idempotency-Key': options.idempotencyKey,
        ...this.securityHeaders(options.security),
        ...options.headers,
      },
    body: JSON.stringify(body),
    });
  }
  async getProject(params: { project_id: string }, options: AuthenticatedOptions = {}): Promise<unknown> {
    return this.request(`/api/v1/projects/${encodeURIComponent(params.project_id)}`, {
      method: "GET",
      headers: {
        ...this.securityHeaders(options.security),
        ...options.headers,
      },
    });
  }
  async listProjectActivity(params: { project_id: string }, options: AuthenticatedOptions = {}): Promise<unknown> {
    return this.request(`/api/v1/projects/${encodeURIComponent(params.project_id)}/activity`, {
      method: "GET",
      headers: {
        ...this.securityHeaders(options.security),
        ...options.headers,
      },
    });
  }
  async login(params: Record<string, never>, body: unknown, options: RequestOptions = {}): Promise<unknown> {
    return this.request(`/api/v1/session/login`, {
      method: "POST",
      headers: {
        ...this.securityHeaders(options.security),
        ...options.headers,
      },
    body: JSON.stringify(body),
    });
  }
  async recordDecision(params: { project_id: string }, body: unknown, options: VersionedMutationOptions): Promise<unknown> {
    return this.request(`/api/v1/projects/${encodeURIComponent(params.project_id)}/decisions`, {
      method: "POST",
      headers: {
      'Idempotency-Key': options.idempotencyKey,
      'If-Match': options.expectedVersion,
        ...this.securityHeaders(options.security),
        ...options.headers,
      },
    body: JSON.stringify(body),
    });
  }

  private async request(path: string, init: RequestInit): Promise<unknown> {
    const response = await this.fetcher(`${this.baseUrl}${path}`, {
      ...init,
      credentials: "same-origin",
      headers: { "Content-Type": "application/json", ...init.headers },
    });
    const payload: unknown = await response.json();
    if (!response.ok) throw new WorkplaneProblem(response.status, payload);
    return payload;
  }

  private securityHeaders(security?: RequestSecurity): Record<string, string> {
    if (security?.kind === "agent-bearer") {
      return { Authorization: `Bearer ${security.bearerToken}` };
    }
    if (security?.kind === "human-session" && security.csrfToken !== undefined) {
      return { "X-CSRF-Token": security.csrfToken };
    }
    return {};
  }
}

export class WorkplaneProblem extends Error {
  constructor(public readonly status: number, public readonly payload: unknown) {
    super(`Workplane request failed (${status})`);
  }
}
