#!/usr/bin/env bash
# shellcheck disable=SC2016 # Markdown backticks below are intentional literals.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT" || exit 1

OUT="${1:-target/release-evidence/release-transcript.md}"
TMP="$(mktemp)"
mkdir -p "$(dirname "$OUT")"

set +e
scripts/acceptance.sh >"$TMP" 2>&1
status=$?
set -e

{
    printf '# Release Transcript\n\n'
    printf 'Generated by `scripts/release-transcript.sh` from local commands only.\n\n'
    printf '## Command\n\n'
    printf '```sh\nscripts/acceptance.sh\n```\n\n'
    printf '## Exit Status\n\n'
    printf '`%s`\n\n' "$status"
    printf '## Output\n\n'
    printf '```text\n'
    cat "$TMP"
    printf '```\n'
} >"$OUT"

cat "$TMP"
printf 'release transcript: %s\n' "$OUT"
rm -f "$TMP"
exit "$status"
